### ISSUE TITLE
Use query param in url to track state

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/explorer-ui#104]
Right now, if send someone the link it always goes back to the first page. We should have page query param in URL and that be the state tracker so you always can land on the exact page you were looking at before.

## Implementation details

Add ?page=<num> to list view urls and fetch transfers based on that.

**Comment by wainola** [comment]
@LyonSsS here is the URL of the deployed branch for QA: https://feat-use-query-param.explorer-ui-qxq.pages.dev/

**Comment by wainola** [comment]
@LyonSsS point 1 has been fixed. It was fecthing the correct page but it wasn't updating the page number. I'm going to check point 2 and 3.

**Comment by LyonSsS** [comment]
Retest: 
1. Issue fixed
2. Issue fixed 
**3**. Issue fixed, but introduced a new issue for any new tab page of aby tx detail 
<img width="1847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODlyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42255a774921bd586667e035bc4d03746d56f95b/image.png" alt="image.png" />
This is different from https://github.com/sygmaprotocol/explorer-ui/issues/154, since here the details are not shown even from the same context page
4. Issue fixed - now it keeps the page context even at clear cache and hard refresh. ( including cache refresh of the entire page app)

**Comment by wainola** [comment]
@LyonSsS issue 3 is linked to #154 because the same logic should be applied for both. Do I get QA approve for this?

**Comment by LyonSsS** [comment]
Thanks for clarifying this one @wainola . This issue is now consider as done. The other issue is out of scope to the context of this one. 
Closing it.
